### ISSUE TITLE
Incorporate Initial Feedback on First Draft 

### ISSUE THREAD

**Issue by lucyrose93** [foundersandcoders/Workshop-Software-Architecture-Design#2]

**Comment by Brymon** [comment]
Could you provide more details on this problem please @lucyrose93 ? ;)

**Comment by zurda** [comment]
@lucyrose93  Could you provide more details on this problem please?

**Comment by astroash** [comment]
judging by dates assume this was fixed in https://github.com/foundersandcoders/Workshop-Software-Architecture-Design/pull/3
